name: bee_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # 腾讯云:
#  tencent_cloud_chat_uikit: ^2.6.0+1
  tencent_calls_uikit:
    path: ./plugins/tencent_calls_uikit-2.3.6
#  tencent_cloud_chat_push: ^7.9.5668+1
#  tencent_cloud_chat_vote_plugin: ^1.0.2
#  tencent_cloud_chat_customer_service_plugin: ^0.0.2
  tencent_cloud_chat_uikit:
    path: ./plugins/TIM_UIKit
#  tencent_calls_uikit: ^2.3.0
#  tencent_cloud_chat_push: ^7.9.5668+1
  # 计算userSign用的
  archive: ^3.6.1

  # 百度地图
  flutter_baidu_mapapi_map: ^3.7.1
  flutter_baidu_mapapi_utils: ^3.7.1
  flutter_baidu_mapapi_search: ^3.7.1
  flutter_bmflocation: ^3.6.0
  gif_view: ^0.4.4

  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^6.0.3
  # 本地存储
  shared_preferences: ^2.2.3
  # tost & loading
  flutter_smart_dialog: ^4.9.7+7
  # 网络库 https://github.com/flutterchina/dio
  dio: ^5.5.0
  # 监听网络状态
  connectivity_plus: ^3.0.4
  # 视频播放
  video_player: ^2.9.1
  # 加密
  crypto: ^3.0.3
  #
  intl: ^0.19.0
  # 富文本
  easy_rich_text: ^2.1.0
  # 首字母排序列表组件
  azlistview: ^2.0.0
  # 汉字转拼音
  lpinyin: ^2.0.0
  # 网络图片缓存加载
  cached_network_image: ^3.3.1
  # 下拉刷新
  flutter_easyrefresh: ^2.2.1
  # 弹窗小组件
  super_tooltip: ^2.0.7
  # 扫一扫
  mobile_scanner: ^5.1.1
  # 官方输入框的扩展组件，支持图片，@某人，自定义文字背景。也支持自定义菜单和选择器。
  extended_text_field: ^16.0.0
  # 特殊文本效果（比如图片，@人）,自定义背景，自定义文本溢出效果,文本选择以及自定义选择菜单和选择器
  extended_text: ^14.0.0
  transparent_image: ^2.0.1
  url_launcher: ^6.3.0
#  http: ^1.0.0
  device_info_plus: ^9.0.3
  # 保存图片到相册
  image_gallery_saver: ^2.0.3
  just_audio: ^0.9.39
  # 字符串生成二维码
  qr_flutter: ^4.1.0
  # 仿微信图片选择: https://pub.flutter-io.cn/packages/wechat_assets_picker
  #  wechat_assets_picker: ^8.9.0-dev.1
  wechat_assets_picker:
    path: ./plugins/wechat_assets_picker-8.9.0-dev.1
  heif_converter: ^1.0.0
  # 九宫格图片浏览
  photo_browser: ^3.0.3
  #Banner控件
  carousel_slider: ^5.0.0
  # app信息
  package_info_plus: ^8.0.0
  # 图片处理（压缩）
  flutter_image_compress: ^1.1.3
  # 图片处理（裁剪）
  image_cropper: ^5.0.1
  # app更新
  flutter_app_update: ^3.1.0
  # 富文本显示
  flutter_html: ^3.0.0-beta.2
  # 权限
  permission_handler: ^11.3.1
  # 虚线
  flutter_dash: ^1.0.0
  # 文件存储管理
  path_provider: ^2.0.8
  # 播放铃声
  flutter_ringtone_player: ^4.0.0+3
  # 震动
  vibration: ^1.9.0
  # 跳转三方地图
  map_launcher: ^3.5.0

  #页面初始化等工具
  xxc_flutter_utils:
    git:
      url: https://github.com/rdchgaa/xxc_flutter_utils.git
      ref: 0bf9a42
  extended_image: ^8.1.0
#  flutter_slidable: 3.1.1
#  google_maps_flutter: 2.9.0
#  geolocator: 11.1.0
  plugin_six2:
    git:
      url: https://github.com/rdchgaa/plugin_six.git
      ref: 6bae85e

  # 列表左滑功能
  flutter_slidable: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/data/
    - assets/images/
    - assets/images/common/
    - assets/images/login_register/
    - assets/images/tabbar/
    - assets/images/home/
    - assets/images/im/
    - assets/images/dynamic/
    - assets/images/user/
    - assets/images/assets/
    - assets/images/share/
    - assets/images/mine/
    #    - assets/svgs/
    - assets/abi/
    - assets/fonts/
    - assets/video/
    - assets/gifs/
    - assets/audios/

    - assets/assets_six/
    - assets/assets_six/languages/
    - assets/assets_six/emojis/
    - assets/assets_six/images/
    - assets/assets_six/html/zh/
    - assets/assets_six/html/en/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

dependency_overrides:
  wechat_assets_picker:
    path: ./plugins/wechat_assets_picker-8.9.0-dev.1
  extended_image: ^8.1.0
  flutter_svg: 2.0.6
  package_info_plus: 8.0.0